exports.run = function (bot, msg) {
    msg.edit(":100::100::100::100::100::100::100::100::100::100::100::100::100:\n:100::volleyball::volleyball::volleyball::volleyball::volleyball::volleyball::volleyball::volleyball::volleyball::volleyball::volleyball::100:\n:100::volleyball::bust_in_silhouette::volleyball::volleyball::volleyball::bust_in_silhouette::bust_in_silhouette::bust_in_silhouette::bust_in_silhouette::bust_in_silhouette::volleyball::100:\n:100::volleyball::bust_in_silhouette::volleyball::volleyball::volleyball::bust_in_silhouette::volleyball::volleyball::volleyball::volleyball::volleyball::100:\n:100::volleyball::bust_in_silhouette::volleyball::volleyball::volleyball::bust_in_silhouette::volleyball::volleyball::volleyball::volleyball::volleyball::100:\n:100::volleyball::bust_in_silhouette::volleyball::volleyball::volleyball::bust_in_silhouette::volleyball::volleyball::volleyball::volleyball::volleyball::100:\n:100::volleyball::bust_in_silhouette::bust_in_silhouette::bust_in_silhouette::bust_in_silhouette::bust_in_silhouette::bust_in_silhouette::bust_in_silhouette::bust_in_silhouette::bust_in_silhouette::volleyball::100:\n:100::volleyball::volleyball::volleyball::volleyball::volleyball::bust_in_silhouette::volleyball::volleyball::volleyball::bust_in_silhouette::volleyball::100:\n:100::volleyball::volleyball::volleyball::volleyball::volleyball::bust_in_silhouette::volleyball::volleyball::volleyball::bust_in_silhouette::volleyball::100:\n:100::volleyball::volleyball::volleyball::volleyball::volleyball::bust_in_silhouette::volleyball::volleyball::volleyball::bust_in_silhouette::volleyball::100:\n:100::volleyball::bust_in_silhouette::bust_in_silhouette::bust_in_silhouette::bust_in_silhouette::bust_in_silhouette::volleyball::volleyball::volleyball::bust_in_silhouette::volleyball::100:\n:100::volleyball::volleyball::volleyball::volleyball::volleyball::volleyball::volleyball::volleyball::volleyball::volleyball::volleyball::100:\n:100::100::100::100::100::100::100::100::100::100::100::100::100:")
};

exports.info = {
    name: 'hitler',
    usage: 'hitler',
    description: 'mein kampf'
};
